mimimi_site_homepage:
    resource: "@MimimiSiteBundle/Controller/MainController.php"
    type:     annotation
mimimi_site_splash:
    resource: "@MimimiSiteBundle/Controller/SplashController.php"
    type:     annotation
mimimi_site_userpage:
    resource: "@MimimiSiteBundle/Controller/UserController.php"
    type:     annotation
mimimi_site_itempage:
    resource: "@MimimiSiteBundle/Controller/ItemController.php"
    type:     annotation