parameters:
#    mimimi_site.example.class: Mimimi\Bundle\SiteBundle\Example

services:
#    mimimi_site.example:
#        class: %mimimi_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
 mimimi_site.users.action_listener:
        class: Mimimi\Bundle\SiteBundle\EventListener\UserListener
        arguments: ["@router", "@session"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }